language: php

##services:

##env:

matrix:
  include:
    - php: 5.3
      dist: precise
    - 5.4
    - 5.5
    - 7.0

before_script:
  - composer install

script:
  - cd tests/phpunit ; phpunit --testsuite marketo-soap-api-client
